version: '3.7'

services:
  privategpt:
    container_name: privategpt
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - PERSIST_DIRECTORY=${PERSIST_DIRECTORY}
      - MODEL_TYPE=${MODEL_TYPE}
      - MODEL_PATH=${MODEL_PATH}
      - EMBEDDINGS_MODEL_NAME=${EMBEDDINGS_MODEL_NAME}
      - MODEL_N_CTX=${MODEL_N_CTX}
      - MODEL_N_BATCH=${MODEL_N_BATCH}
      - TARGET_SOURCE_CHUNKS=${TARGET_SOURCE_CHUNKS}
